### PR TITLE
chore: cache node_modules

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by typicode** [comment]
Hi @DanielRuf,

For very small modules or not so popular ones, I prefer to stick to basic `.travis` config and not tweak it too much.

But if you want to add cache to these projects https://github.com/typicode/json-server, https://github.com/typicode/lowdb and https://github.com/typicode/hotel, which have more dependencies, I'd be happy to merge :+1: 

If you create PRs, please add the `cache` field just the `node_js` for consistency.

**Comment by DanielRuf** [comment]
> If you create PRs, please add the cache field just the node_js for consistency.

I do not fully understand.

**Comment by typicode** [comment]
My bad >< it's missing a word, sorry. I wanted to say "just *after* the `node_js` field"

```yaml
# ...
node_js:
  - "node"
  - "6"
cache: 
  directories:
    - "node_modules"
# ...

**Comment by DanielRuf** [comment]
> My bad >< it's missing a word, sorry. I wanted to say "just after the node_js field"

It is / was? => https://github.com/typicode/please-upgrade-node/pull/14/files

**Comment by typicode** [comment]
Yes, it is :)

But as said, I'd prefer to stick to basic `.travis.yml` config, with just the bare minimum, for small projects like this one. Sorry if it wasn't clear.

On the other side, for bigger projects like JSON Server, LowDB and Hotel, adding `cache` would be welcome.

**Pull request closed without merging**
